upstream spring_backend {
    server spring1:8080;
    server spring2:8080;
    server spring3:8080;
}

server {
    listen 80;

    location / {
        proxy_pass http://spring_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        add_header X-Upstream-Server $upstream_addr always;
    }
}
