spring.application.name=ticketing

# === Profile ===
# local 프로파일에서만 DataSeedRunner 활성화
spring.profiles.active=local

# === JWT ===
jwt.secret=${JWT_SECRET:dev-only-secret-key-must-be-at-least-32-bytes-long-12345}
jwt.access-token-expiration=1800000
jwt.refresh-token-expiration=1209600000


# === DataSource ===
spring.datasource.url=jdbc:mysql://localhost:3306/ticketing?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&rewriteBatchedStatements=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:qwer1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === JPA ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# === Redis ===
spring.data.redis.host=localhost
spring.data.redis.port=6379

# === prometheus ===
management.endpoints.web.exposure.include=prometheus,health
management.metrics.tags.application=ticketing